version: '3'
services: 
  api:
    container_name: 'forgetful-bartender-api'
    build:
      context: ..
      dockerfile: ./build/package/deployment.dockerfile
    ports:
      - '8081:8081'
  mongo:
    image: 'mongo:latest'
    container_name: 'forgetful-bartender-db'
    ports:
      - '27017:27017'